version: '3'

services:
  server:
    build: ../djangoTemplate copy
    container_name: server
    command: python manage.py runserver '0.0.0.0:5000'
    volumes:
      - .:/app
    ports:
      - '5000:5000'