# Generated by Django 5.1.1 on 2024-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileCoordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
            ],
            options={
                "db_table": "mens_pants",
            },
        ),
    ]
